import java.util.Scanner;
public class bentukMain {
    public static void main(String[] args){
        Scanner input=new Scanner (System.in);
        System.out.println("Latihan 1");
        System.out.print("Warna Bentuk            : ");
        String warna=input.next();
       bentukClass b1=new bentukClass("Merah");
       bentukClass b2=new bentukClass("Biru");
       bentukClass b3=new bentukClass("Ungu");
       b1.setWarna(warna);
        System.out.println("Contoh Scanner");
       b1.info();
        System.out.println("Contoh constructor");
       b2.info();
       b3.setWarna("Biru");
        System.out.println("Contoh tanpa constructor");
       b3.info();
        System.out.print("Warna Bujur Sangkar     : ");
        String warnakotak=input.next();
        System.out.print("Sisi Bujur Sangkar      : ");
        double sisi=input.nextDouble();
        kotak k1=new kotak("Putih",4);
        kotak k2=new kotak("Biru",6);
        kotak k3=new kotak("Kuning",8);
         k1.setWarna(warnakotak);
         k1.setSisi(sisi);
        System.out.println("Contoh Scanner");
       k1.infoKotak();
        System.out.println("Contoh constructor");
       k2.infoKotak();
       k3.setWarna("Jingga");
       k3.setSisi(10);
        System.out.println("Contoh tanpa constructor");
       k3.infoKotak();
        System.out.println();
        System.out.println("Latihan 2");
        System.out.print("Warna Lingkaran         : ");
        String warnabulet=input.next();
        System.out.print("Radius Lingkaran        : ");
        double radius=input.nextDouble();
        lingkaran L1=new lingkaran("Biru",14);
        lingkaran L2=new lingkaran("Kuning",21);
        lingkaran L3=new lingkaran("Hitam",28);
        L1.setRadius(radius);
        L1.setWarna(warnabulet);
        System.out.println("Contoh Scanner");
       L1.infoLingkaran();
        System.out.println("Contoh constructor");
       L2.infoLingkaran();
       L3.setWarna("Hitam");
       L3.setRadius(35);
        System.out.println("Contoh tanpa constructor");
       L3.infoLingkaran();
        System.out.println();
        System.out.println("Latihan 3");
        System.out.print("Warna Tabung            : ");
        String warnatab=input.next();
        System.out.print("Radius Tabung           : ");
        double radtab=input.nextDouble();
        System.out.print("Tinggi Tabung           : ");
        double tinggi=input.nextDouble();
        tabung t1=new tabung("Merah",49,5);
        tabung t2=new tabung("Hitam",7,10);
        tabung t3=new tabung("Hijau",14,20);
        t1.setRadius(radtab);
        t1.setTinggi(tinggi);
        t1.setWarna(warnatab);
        System.out.println("Contoh Scanner");
       t1.infoTabung();
        System.out.println("Contoh constructor");
       t2.infoTabung();
       t3.setWarna("Ungu");
       t3.setRadius(7);
       t3.setTinggi(20);
        System.out.println("Contoh tanpa constructor");
       t3.infoTabung();
    }
}
