
import java.awt.HeadlessException;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ASUS
 */
public class mobilebank extends javax.swing.JFrame {

    /**
     * Creates new form mobilebank
     */
    public mobilebank() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        saldo = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        awalan = new javax.swing.JPanel();
        menu = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        info = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        home = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        transfer = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        rekening = new javax.swing.JTextField();
        jumlahtransfer = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        pulsa = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        telepon = new javax.swing.JTextField();
        jumlahpulsa = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        pln = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        nomormeter = new javax.swing.JTextField();
        jumlahpln = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        pdam = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ovo = new javax.swing.JTextField();
        jumlahovo = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setText("876530982456");

        saldo.setText("5000000");

        jLabel8.setText("Rp");

        jLabel14.setText("No. Rekening");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(saldo, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saldo, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(jLabel8))
                .addContainerGap())
        );

        awalan.setBackground(new java.awt.Color(255, 255, 0));
        awalan.setLayout(new java.awt.CardLayout());

        menu.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setToolTipText("");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });

        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });

        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });

        jLabel31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel31MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(86, 86, 86)
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12)
                    .addGroup(menuLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel31)))
                .addContainerGap(191, Short.MAX_VALUE))
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel12))
                .addGap(34, 34, 34)
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel10))
                .addGap(29, 29, 29)
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(menuLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel31)))
                .addContainerGap(205, Short.MAX_VALUE))
        );

        awalan.add(menu, "card8");

        info.setBackground(new java.awt.Color(255, 255, 255));
        info.setPreferredSize(new java.awt.Dimension(399, 378));

        jLabel15.setText("Nama Lengkap  ");

        jLabel16.setText("Alamat               ");

        jLabel17.setText("TTL                    ");

        jLabel18.setText("Email                 ");

        jLabel19.setText("Pekerjaan         ");

        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
        });

        jLabel3.setText("PUTU NUR MAULINA TANTYA");

        jLabel4.setText("JALAN RAYA ITS, SURABAYA");

        jLabel5.setText("SURABAYA, 1 JANUARI 2000");

        jLabel6.setText("pnmt123@gmail.com");

        jLabel7.setText("MAHASISWI");

        javax.swing.GroupLayout infoLayout = new javax.swing.GroupLayout(info);
        info.setLayout(infoLayout);
        infoLayout.setHorizontalGroup(
            infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoLayout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addGroup(infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19))
                .addGap(40, 40, 40)
                .addGroup(infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, infoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(home)
                .addGap(81, 81, 81))
        );
        infoLayout.setVerticalGroup(
            infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel7))
                .addGap(94, 94, 94)
                .addComponent(home)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        awalan.add(info, "card10");

        transfer.setBackground(new java.awt.Color(255, 255, 255));
        transfer.setPreferredSize(new java.awt.Dimension(399, 378));

        jLabel20.setText("Nomor Rekening");

        jLabel21.setText("Nominal");

        rekening.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rekeningActionPerformed(evt);
            }
        });

        jLabel26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel26MouseClicked(evt);
            }
        });

        jLabel28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel28MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout transferLayout = new javax.swing.GroupLayout(transfer);
        transfer.setLayout(transferLayout);
        transferLayout.setHorizontalGroup(
            transferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transferLayout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addGroup(transferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(transferLayout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addGap(163, 163, 163)
                        .addComponent(jLabel28))
                    .addGroup(transferLayout.createSequentialGroup()
                        .addGroup(transferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel20))
                        .addGap(35, 35, 35)
                        .addGroup(transferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jumlahtransfer, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(rekening))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        transferLayout.setVerticalGroup(
            transferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transferLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(transferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(rekening, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(transferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jumlahtransfer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(transferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jLabel28))
                .addContainerGap(139, Short.MAX_VALUE))
        );

        awalan.add(transfer, "card11");

        pulsa.setBackground(new java.awt.Color(255, 255, 255));
        pulsa.setPreferredSize(new java.awt.Dimension(399, 378));

        jLabel22.setText("Nomor Telepon");

        jLabel23.setText("Nominal");

        jLabel29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel29MouseClicked(evt);
            }
        });

        jLabel30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel30MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pulsaLayout = new javax.swing.GroupLayout(pulsa);
        pulsa.setLayout(pulsaLayout);
        pulsaLayout.setHorizontalGroup(
            pulsaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pulsaLayout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addGroup(pulsaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel29)
                    .addGroup(pulsaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel23)
                        .addComponent(jLabel22)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(pulsaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pulsaLayout.createSequentialGroup()
                        .addGroup(pulsaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jumlahpulsa, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(telepon))
                        .addGap(60, 60, 60))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pulsaLayout.createSequentialGroup()
                        .addComponent(jLabel30)
                        .addGap(86, 86, 86))))
        );
        pulsaLayout.setVerticalGroup(
            pulsaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pulsaLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(pulsaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(telepon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pulsaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jumlahpulsa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pulsaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel29)
                    .addComponent(jLabel30))
                .addContainerGap(145, Short.MAX_VALUE))
        );

        awalan.add(pulsa, "card12");

        pln.setBackground(new java.awt.Color(255, 255, 255));
        pln.setPreferredSize(new java.awt.Dimension(399, 378));

        jLabel24.setText("ID Pelanggan");

        jLabel25.setText("Nominal");

        jLabel32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel32MouseClicked(evt);
            }
        });

        jLabel33.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel33MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout plnLayout = new javax.swing.GroupLayout(pln);
        pln.setLayout(plnLayout);
        plnLayout.setHorizontalGroup(
            plnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plnLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(plnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(plnLayout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addGap(87, 87, 87)
                        .addComponent(jumlahpln))
                    .addGroup(plnLayout.createSequentialGroup()
                        .addGroup(plnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel32)
                            .addComponent(jLabel24))
                        .addGroup(plnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(plnLayout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(nomormeter, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, plnLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel33)))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        plnLayout.setVerticalGroup(
            plnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plnLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(plnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(nomormeter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(plnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jumlahpln, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(plnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel32)
                    .addComponent(jLabel33))
                .addContainerGap(104, Short.MAX_VALUE))
        );

        awalan.add(pln, "card13");

        pdam.setBackground(new java.awt.Color(255, 255, 255));
        pdam.setPreferredSize(new java.awt.Dimension(399, 378));

        jLabel27.setText("Nomor Telepon");

        jLabel2.setText("Nominal");

        ovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ovoActionPerformed(evt);
            }
        });

        jLabel34.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel34MouseClicked(evt);
            }
        });

        jLabel35.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel35MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pdamLayout = new javax.swing.GroupLayout(pdam);
        pdam.setLayout(pdamLayout);
        pdamLayout.setHorizontalGroup(
            pdamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pdamLayout.createSequentialGroup()
                .addGroup(pdamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pdamLayout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addGroup(pdamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel27)
                            .addComponent(jLabel2)))
                    .addGroup(pdamLayout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(jLabel34)))
                .addGap(64, 64, 64)
                .addGroup(pdamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pdamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jumlahovo, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                        .addComponent(ovo))
                    .addComponent(jLabel35))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        pdamLayout.setVerticalGroup(
            pdamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pdamLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(pdamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(ovo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pdamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jumlahovo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(pdamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(jLabel35))
                .addContainerGap(95, Short.MAX_VALUE))
        );

        awalan.add(pdam, "card14");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(awalan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(awalan, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rekeningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rekeningActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rekeningActionPerformed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
          awalan.removeAll();
        awalan.add(info);
        awalan.repaint();
        awalan.revalidate();
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
         awalan.removeAll();
        awalan.add(transfer);
        awalan.repaint();
        awalan.revalidate();
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
         awalan.removeAll();
        awalan.add(pulsa);
        awalan.repaint();
        awalan.revalidate();
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        awalan.removeAll();
        awalan.add(pln);
        awalan.repaint();
        awalan.revalidate();
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        awalan.removeAll();
        awalan.add(pdam);
        awalan.repaint();
        awalan.revalidate();
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel31MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel31MouseClicked
        dispose();
    }//GEN-LAST:event_jLabel31MouseClicked

    private void ovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ovoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ovoActionPerformed

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
        awalan.removeAll();
        awalan.add(menu);
        awalan.repaint();
        awalan.revalidate();
    }//GEN-LAST:event_homeMouseClicked

    private void jLabel26MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel26MouseClicked
        try{ 
            if("".equals(rekening.getText())||"".equals(jumlahtransfer.getText())){
            JOptionPane.showMessageDialog(null,"Semua data harus diisi","Error",JOptionPane.ERROR_MESSAGE);
        } else { 
            if(rekening.getText().length()!=12){
                JOptionPane.showMessageDialog(null,"Masukkan data dengan benar",
                        "Error",JOptionPane.ERROR_MESSAGE);
                rekening.setText("");
                jumlahtransfer.setText("");
            } else if("876530982456".equals(rekening.getText())){
                JOptionPane.showMessageDialog(null,"Tidak bisa transfer ke rekening sendiri",
                        "Error",JOptionPane.ERROR_MESSAGE);
                rekening.setText("");
            }else{  
                 String s=Long.toString(Long.parseLong(rekening.getText()));
                 
                 Database data=new Database();
                 
                 data.setRekening(rekening.getText());
                 data.setHarga(Long.parseLong(jumlahtransfer.getText()));
                 
                 transfersukses ts=new transfersukses();
                 
                 if(saldotransfer()<0){
                     JOptionPane.showMessageDialog(null,"Saldo tidak cukup",
                             "Error",JOptionPane.ERROR_MESSAGE);
                     jumlahtransfer.setText("");
                     throw new HeadlessException();
                 }
                 
                 ts.saldo(saldotransfer());
                 ts.setHarga(data.getHarga());
                 ts.setRekening(data.getRekening());
                 
                 ts.setVisible(true);
                 dispose();
            }
            
        } 
            
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null,"Masukkan data dengan benar",
                    "Error",JOptionPane.ERROR_MESSAGE);
            rekening.setText("");
            jumlahtransfer.setText("");
        }
        catch (HeadlessException e){
            
        }
    }//GEN-LAST:event_jLabel26MouseClicked

    private void jLabel28MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel28MouseClicked
        awalan.removeAll();
        awalan.add(menu);
        awalan.repaint();
        awalan.revalidate();
    }//GEN-LAST:event_jLabel28MouseClicked

    private void jLabel29MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel29MouseClicked
                try{
             String a=Long.toString(Long.parseLong(telepon.getText()));
    
            if("".equals(telepon.getText())||"".equals(jumlahpulsa.getText())){
            JOptionPane.showMessageDialog(null,"Semua data harus diisi","Error",JOptionPane.ERROR_MESSAGE);
        } else { 
            if(telepon.getText().length()!=12){
                JOptionPane.showMessageDialog(null,"Masukkan data dengan benar",
                        "Error",JOptionPane.ERROR_MESSAGE);
                telepon.setText("");
                jumlahpulsa.setText("");
            } else {
              
                 Database data=new Database();
                 
                 data.setTelepon(telepon.getText());
                 data.setHarga(Long.parseLong(jumlahpulsa.getText()));
                 
                 pulsasukses pls=new pulsasukses();
                 
                 if(saldopulsa()<0){
                     JOptionPane.showMessageDialog(null,"Saldo tidak cukup",
                             "Error",JOptionPane.ERROR_MESSAGE);
                     jumlahpulsa.setText("");
                     throw new HeadlessException();
                 }
                 
                 pls.saldo(saldopulsa());
                 pls.setHarga(data.getHarga());
                 pls.setTelepon(data.getTelepon());
                 
                 pls.setVisible(true);
                 dispose();
            }
            
        }
         } catch(NumberFormatException e){
             JOptionPane.showMessageDialog(null,"Masukkan data dengan benar",
                     "Error",JOptionPane.ERROR_MESSAGE);
         }

        catch (HeadlessException e){
            
        }

    }//GEN-LAST:event_jLabel29MouseClicked

    private void jLabel30MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel30MouseClicked
        awalan.removeAll();
        awalan.add(menu);
        awalan.repaint();
        awalan.revalidate();
    }//GEN-LAST:event_jLabel30MouseClicked

    private void jLabel32MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel32MouseClicked
                try{
             String a=Long.toString(Long.parseLong(nomormeter.getText()));
    
            if("".equals(nomormeter.getText())||"".equals(jumlahpln.getText())){
            JOptionPane.showMessageDialog(null,"Semua data harus diisi","Error",JOptionPane.ERROR_MESSAGE);
        } else { 
            if(nomormeter.getText().length()!=11){
                JOptionPane.showMessageDialog(null,"Masukkan data dengan benar",
                        "Error",JOptionPane.ERROR_MESSAGE);
                nomormeter.setText("");
                jumlahpln.setText("");
            } else {
                 long b=(long) (999999*Math.random());
                 long c=(long) (999999*Math.random());
                 long d=(long) (9999999*Math.random());
                 Database data=new Database();
                 
                 data.setNomormeter(nomormeter.getText());
                 data.setHarga(Long.parseLong(jumlahpln.getText()));
                 data.setToken1(b);
                 data.setToken2(c);
                 data.setToken3(d);
                 plnsukses pl=new plnsukses();
                 
                 if(saldopln()<0){
                     JOptionPane.showMessageDialog(null,"Saldo tidak cukup",
                             "Error",JOptionPane.ERROR_MESSAGE);
                     jumlahpln.setText("");
                     throw new HeadlessException();
                 }
                 
                 pl.saldo(saldopln());
                 pl.setHarga(data.getHarga());
                 pl.setNomormeter(data.getNomormeter());
                 pl.setToken1(Long.toString(data.getToken1()));
                 pl.setToken2(Long.toString(data.getToken2()));
                 pl.setToken3(Long.toString(data.getToken3()));
                 pl.setVisible(true);
                 dispose();
            }
            
        }
         } catch(NumberFormatException e){
             JOptionPane.showMessageDialog(null,"Masukkan data dengan benar",
                     "Error",JOptionPane.ERROR_MESSAGE);
         }

        catch (HeadlessException e){
            
        }

    }//GEN-LAST:event_jLabel32MouseClicked

    private void jLabel34MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel34MouseClicked
                try{
             String a=Long.toString(Long.parseLong(ovo.getText()));
    
            if("".equals(ovo.getText())||"".equals(jumlahovo.getText())){
            JOptionPane.showMessageDialog(null,"Semua data harus diisi","Error",JOptionPane.ERROR_MESSAGE);
        } else { 
            if(ovo.getText().length()!=12){
                JOptionPane.showMessageDialog(null,"Masukkan data dengan benar",
                        "Error",JOptionPane.ERROR_MESSAGE);
                ovo.setText("");
                jumlahovo.setText("");
            } else {
              
                 Database data=new Database();
                 
                 data.setPdam(ovo.getText());
                 data.setHarga(Long.parseLong(jumlahovo.getText()));
                 
                 pdamsukses pd=new pdamsukses();
                 
                 if(saldoovo()<0){
                     JOptionPane.showMessageDialog(null,"Saldo tidak cukup",
                             "Error",JOptionPane.ERROR_MESSAGE);
                     jumlahovo.setText("");
                     throw new HeadlessException();
                 }
                 
                 pd.saldo(saldoovo());
                 pd.setHarga(data.getHarga());
                 pd.setPdam(data.getPdam());
                 
                 pd.setVisible(true);
                 dispose();
            }
            
        }
         } catch(NumberFormatException e){
             JOptionPane.showMessageDialog(null,"Masukkan data dengan benar",
                     "Error",JOptionPane.ERROR_MESSAGE);
         }

        catch (HeadlessException e){
            
        }

    }//GEN-LAST:event_jLabel34MouseClicked

    private void jLabel35MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel35MouseClicked
                awalan.removeAll();
        awalan.add(menu);
        awalan.repaint();
        awalan.revalidate();

    }//GEN-LAST:event_jLabel35MouseClicked

    private void jLabel33MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel33MouseClicked
awalan.removeAll();
        awalan.add(menu);
        awalan.repaint();
        awalan.revalidate();
    }//GEN-LAST:event_jLabel33MouseClicked
 public long saldopln() {
        long saldoawal = Long.parseLong(saldo.getText());
        long saldoakhir = saldoawal - Long.parseLong(jumlahpln.getText());
        return saldoakhir;
   }
  public long saldopulsa() {
        long saldoawal = Long.parseLong(saldo.getText());
        long saldoakhir = saldoawal - Long.parseLong(jumlahpulsa.getText());
        return saldoakhir;
   }
  public long saldotransfer() {
        long saldoawal = Long.parseLong(saldo.getText());
        long saldoakhir = saldoawal - Long.parseLong(jumlahtransfer.getText());
        return saldoakhir;
   }
  public long saldoovo() {
        long saldoawal = Long.parseLong(saldo.getText());
        long saldoakhir = saldoawal - Long.parseLong(jumlahovo.getText());
        return saldoakhir;
   }
    public void saldoakhir(String saldodo) {
        saldo.setText(saldodo);
    }
    public void saldo(long sisasaldoku) {
        saldo.setText(String.valueOf(sisasaldoku));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mobilebank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mobilebank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mobilebank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mobilebank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mobilebank().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel awalan;
    private javax.swing.JLabel home;
    private javax.swing.JPanel info;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jumlahovo;
    private javax.swing.JTextField jumlahpln;
    private javax.swing.JTextField jumlahpulsa;
    private javax.swing.JTextField jumlahtransfer;
    private javax.swing.JPanel menu;
    private javax.swing.JTextField nomormeter;
    private javax.swing.JTextField ovo;
    private javax.swing.JPanel pdam;
    private javax.swing.JPanel pln;
    private javax.swing.JPanel pulsa;
    private javax.swing.JTextField rekening;
    private javax.swing.JLabel saldo;
    private javax.swing.JTextField telepon;
    private javax.swing.JPanel transfer;
    // End of variables declaration//GEN-END:variables
}