
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ASUS
 */
public class pancasila extends javax.swing.JFrame {

    /**
     * Creates new form pancasila
     */
    public pancasila() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kotaasal = new javax.swing.JComboBox<>();
        kotatujuan = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        kotaasal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D" }));

        kotatujuan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D" }));

        jButton1.setText("Proses");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Keluar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Asal");

        jLabel2.setText("Tujuan");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                                .addComponent(jButton2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(kotaasal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(kotatujuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(96, 96, 96))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(94, 94, 94))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kotaasal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kotatujuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(150, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(kotaasal.getSelectedIndex()==0&&kotatujuan.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(null,"Pilih yang benar","Error",JOptionPane.ERROR_MESSAGE);
        } else if(kotaasal.getSelectedIndex()==1&&kotatujuan.getSelectedIndex()==1){
            JOptionPane.showMessageDialog(null,"Pilih yang benar","Error",JOptionPane.ERROR_MESSAGE);
        } else if(kotaasal.getSelectedIndex()==2&&kotatujuan.getSelectedIndex()==2){
            JOptionPane.showMessageDialog(null,"Pilih yang benar","Error",JOptionPane.ERROR_MESSAGE);
        }else if(kotaasal.getSelectedIndex()==3&&kotatujuan.getSelectedIndex()==3){
            JOptionPane.showMessageDialog(null,"Pilih yang benar","Error",JOptionPane.ERROR_MESSAGE);
        } else if ((kotaasal.getSelectedIndex()==1&&kotatujuan.getSelectedIndex()==0)||(kotaasal.getSelectedIndex()==0&&kotatujuan.getSelectedIndex()==1)){
            DATABASE data=new DATABASE();
            
            data.setHarga(1000000);
            data.setJarak(100);
            
            tampilanakhir t=new tampilanakhir();
            
            t.setHarga(data.getHarga());
            t.setJarak(data.getJarak());
            
            t.setVisible(true);
            dispose();
        } else if((kotaasal.getSelectedIndex()==2&&kotatujuan.getSelectedIndex()==0)||(kotaasal.getSelectedIndex()==0&&kotatujuan.getSelectedIndex()==2)){
             DATABASE data=new DATABASE();
            
            data.setHarga(2000000);
            data.setJarak(200);
            
            tampilanakhir t=new tampilanakhir();
            
            t.setHarga(data.getHarga());
            t.setJarak(data.getJarak());
            
            t.setVisible(true);
            dispose();
        } else if((kotaasal.getSelectedIndex()==3&&kotatujuan.getSelectedIndex()==0)||(kotaasal.getSelectedIndex()==0&&kotatujuan.getSelectedIndex()==3)){
             DATABASE data=new DATABASE();
            
            data.setHarga(3000000);
            data.setJarak(300);
            
            tampilanakhir t=new tampilanakhir();
            
            t.setHarga(data.getHarga());
            t.setJarak(data.getJarak());
            
            t.setVisible(true);
            dispose();
        } else if((kotaasal.getSelectedIndex()==2&&kotatujuan.getSelectedIndex()==1)||(kotaasal.getSelectedIndex()==1&&kotatujuan.getSelectedIndex()==2)){
             DATABASE data=new DATABASE();
            
            data.setHarga(1500000);
            data.setJarak(150);
            
            tampilanakhir t=new tampilanakhir();
            
            t.setHarga(data.getHarga());
            t.setJarak(data.getJarak());
            
            t.setVisible(true);
            dispose();
        } else if((kotaasal.getSelectedIndex()==3&&kotatujuan.getSelectedIndex()==1)||(kotaasal.getSelectedIndex()==1&&kotatujuan.getSelectedIndex()==3)){
            DATABASE data=new DATABASE();
            
            data.setHarga(2500000);
            data.setJarak(250);
            
            tampilanakhir t=new tampilanakhir();
            
            t.setHarga(data.getHarga());
            t.setJarak(data.getJarak());
            
            t.setVisible(true);
            dispose();
        } else if((kotaasal.getSelectedIndex()==3&&kotatujuan.getSelectedIndex()==2)||(kotaasal.getSelectedIndex()==2&&kotatujuan.getSelectedIndex()==3)){
             DATABASE data=new DATABASE();
            
            data.setHarga(1250000);
            data.setJarak(125);
            
            tampilanakhir t=new tampilanakhir();
            
            t.setHarga(data.getHarga());
            t.setJarak(data.getJarak());
            
            t.setVisible(true);
            dispose();
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pancasila.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pancasila.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pancasila.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pancasila.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pancasila().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox<String> kotaasal;
    private javax.swing.JComboBox<String> kotatujuan;
    // End of variables declaration//GEN-END:variables
}
