/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import javax.swing.*;
import java.awt.*;
import javax.swing.UIManager.*;
/**
 *
 * @author ASUS
 */
public class framebendera extends JFrame {
Dimension dimensi = Toolkit.getDefaultToolkit().getScreenSize(); 
    private Container konten = getContentPane();
  gambarBendera bendera = new gambarBendera();
     
 
    public framebendera() {
         super("Gambar Bendera");
        setVisible(true);
        setSize(500,300);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setResizable(false);
        setLocation(dimensi.width/2 - getWidth()/2,dimensi.height/2 - getHeight()/2); //Mengatur Frame tampil di tengah layar monitor
        konten.add(bendera);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
                  try{
                    UIManager.setLookAndFeel("com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel");
                    } catch (UnsupportedLookAndFeelException e) 
                    {
                     
                    } 
                    catch (ClassNotFoundException e)
                    {
                     
                    } 
                    catch (InstantiationException e) 
                    {
                     
                    } 
                    catch (IllegalAccessException e)
                    {
                     
                    }
                    new framebendera();
    }
      
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

