/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import javax.swing.*;
import java.awt.*;
/**
 *
 * @author ASUS
 */
public class gambarBendera extends Canvas {
    public void paint(Graphics graph){
         
        graph.setColor(Color.RED);
        graph.fill3DRect(50, 50, 50, 50,true); // x/y/width/height/raised
        graph.setColor(Color.WHITE);
        graph.drawRect(50, 50, 50, 50); // x/y/width/height/raised
        
         
        graph.setFont(new Font("Calibri",Font.BOLD,15)); // Jenis Font/Tebal/Ukuran Font
        graph.setColor(Color.BLACK);
        graph.drawString("Indonesia Raya", 220, 200); // Text/x/y
        graph.setColor(Color.GRAY);
        graph.draw3DRect(208, 202, 150, 2,true); // x/y/width/height/raised
         
        graph.setFont(new Font("Comic Sans MS",Font.BOLD,12)); //Jenis Font/Tebal/Ukuran
        graph.setColor(Color.BLUE);
        graph.drawString("Design by : Resa C.R", 350, 260);//Text/x/y    
    }
    /**
     * Creates new form gambarBendera
     */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setDefaultCloseOperation(int EXIT_ON_CLOSE) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
//     * @param args the command line arguments
    private Container getContentPane() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    private void pack() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}